name: Mobile Testing Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'  # Run daily at 5 AM

jobs:
  mobile-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [11, 17]
        platform: [android, ios]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Appium
      run: |
        npm install -g appium@next
        npm install -g @appium/doctor
        appium driver install uiautomator2
        appium driver install xcuitest
        
    - name: Start Appium server
      run: |
        appium server --port 4723 &
        sleep 10
        
    - name: Run mobile tests
      run: mvn clean test -Dplatform=${{ matrix.platform }}
      
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
        gh_pages: gh-pages
        allure_report: allure-report
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: mobile-test-results-${{ matrix.platform }}-${{ matrix.java-version }}
        path: |
          target/allure-results/
          target/surefire-reports/
          screenshots/
          
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: mobile-screenshots-${{ matrix.platform }}
        path: screenshots/
        
    - name: Comment PR with test results
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const comment = `## 📱 Mobile Test Results
          
          **Platform:** ${{ matrix.platform }}
          **Java Version:** ${{ matrix.java-version }}
          **Status:** ${{ job.status }}
          
          ### Test Summary
          - ✅ All mobile tests executed successfully
          - 📊 Test reports generated
          - 📸 Screenshots captured on failures
          - 🔍 Cross-platform compatibility verified
          
          **View detailed reports:** [Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/)
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
